name: Cloudflare-RDP
on: 
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Enable Remote Desktop
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

      - name: Create User Account
        run: |
          $Password = ConvertTo-SecureString "Password123!" -AsPlainText -Force
          New-LocalUser -Name "CloudUser" -Password $Password -Description "RDP User"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "CloudUser"
          Add-LocalGroupMember -Group "Administrators" -Member "CloudUser"

      - name: Start Cloudflare Tunnel
        run: |
          curl -L --output cloudflared.exe https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe
          start /B .\cloudflared.exe tunnel --no-autoupdate run --token ${{ secrets.CF_TOKEN }}

      - name: Keep Alive
        run: |
          Write-Host "الآن النفق شغال والدومين الخاص بك مرتبط بالجهاز."
          Write-Host "User: CloudUser"
          Write-Host "Pass: Password123!"
          Start-Sleep -Seconds 21600
